# ARM Toolchain for RP2040, RP2350, nRF52/54
FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    gcc-arm-none-eabi \
    libnewlib-arm-none-eabi \
    python3 \
    python3-pip \
    git \
    wget \
    ninja-build \
    doxygen \
    libsdl2-dev \
    ccache \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

# Install python dependencies
RUN pip3 install --no-cache-dir pyelftools

WORKDIR /build
